import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK_ONLY = process.argv.includes("--check");
const TARGETS = [
  {
    input: "create-job.v1.schema.json",
    output: "src/create-job.ts",
    rootName: "CreateJobSchema",
  },
  {
    input: "job-events.v2.schema.json",
    output: "src/job-events.ts",
    rootName: "JobEventsSchema",
  },
  {
    input: "job-status.v1.schema.json",
    output: "src/job-status.ts",
    rootName: "JobStatusSchema",
  },
  {
    input: "library-books.v1.schema.json",
    output: "src/library-books.ts",
    rootName: "LibraryBooksSchema",
  },
  {
    input: "reader-data.v1.schema.json",
    output: "src/reader-data.ts",
    rootName: "ReaderDataSchema",
  },
];

const GENERATOR_OPTIONS = {
  additionalProperties: false,
  bannerComment: [
    "/* eslint-disable */",
    "/**",
    " * Generated by scripts/generate-types.mjs.",
    " * Do not edit by hand; update the source schema and run npm run generate.",
    " */",
  ].join("\n"),
  declareExternallyReferenced: true,
  enableConstEnums: false,
  format: true,
  ignoreMinAndMaxItems: false,
  strictIndexSignatures: false,
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
  unreachableDefinitions: true,
  unknownAny: false,
};

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/g, "\n");
}

// create-job 的**运行期**字段名清单。
//
// 上面生成的是 TS 类型，类型在运行期不存在；而 mock 层要模拟后端的
// `deny_unknown_fields`（多一个键 => 400），需要的恰恰是一份运行期能读的白名单。
// 在此之前那份白名单是手抄在 frontend/web 的 mock 里的 —— 抄一份就会漂，于是同一
// 个事实有了两个真相源。现在它从 create-job.v1.schema.json 生成，
// `npm run generate:check` 保证它不落后于 schema。
const FIELD_LIST_TARGET = {
  input: "create-job.v1.schema.json",
  output: "src/create-job-fields.ts",
  root: "CreateJobInput",
};

const FIELD_LIST_BANNER = [
  "/* eslint-disable */",
  "/**",
  " * Generated by scripts/generate-types.mjs.",
  " * Do not edit by hand; update the source schema and run npm run generate.",
  " */",
].join("\n");

function refName(node) {
  const ref = node && typeof node === "object" ? node.$ref : undefined;
  if (typeof ref !== "string") return null;
  const prefix = "#/definitions/";
  return ref.startsWith(prefix) ? ref.slice(prefix.length) : null;
}

/**
 * 只有 `additionalProperties: false` 的定义才配拥有一份封闭白名单：
 * 定义本身允许额外字段，却发一张"就这些字段"的表出去，就是对下游撒谎。
 */
function closedFieldNames(schema, name) {
  const definition = schema.definitions?.[name];
  assert.ok(definition, `${FIELD_LIST_TARGET.input} 缺少 definitions.${name}`);
  assert.equal(
    definition.additionalProperties,
    false,
    `definitions.${name} 不是 additionalProperties: false —— 不能为它生成封闭字段白名单`,
  );
  const names = Object.keys(definition.properties ?? {}).sort();
  assert.ok(names.length > 0, `definitions.${name}.properties 是空的 —— 解析写法已失效`);
  return names;
}

function renderFieldList(names, indent) {
  const pad = " ".repeat(indent);
  return names.map((name) => `${pad}${JSON.stringify(name)},`).join("\n");
}

async function generateFieldList() {
  const inputPath = resolve(PACKAGE_ROOT, FIELD_LIST_TARGET.input);
  const outputPath = resolve(PACKAGE_ROOT, FIELD_LIST_TARGET.output);
  const schema = JSON.parse(await readFile(inputPath, "utf8"));

  const topLevel = closedFieldNames(schema, FIELD_LIST_TARGET.root);
  // 段的名字和它对应的定义都从 schema 读，不在这里另抄一张映射表。
  // `workflow` 指向 WorkflowKind（字符串枚举，没有 properties），自然不是段。
  const rootProperties = schema.definitions[FIELD_LIST_TARGET.root].properties;
  const sections = topLevel
    .map((field) => [field, refName(rootProperties[field])])
    .filter(([, definitionName]) => (
      definitionName !== null
      && typeof schema.definitions[definitionName]?.properties === "object"
    ));
  assert.ok(sections.length > 0, `${FIELD_LIST_TARGET.root} 没解析出任何段 —— 解析写法已失效`);

  const generated = `${FIELD_LIST_BANNER}

/** \`CreateJobInput\` 的段名（顶层字段里指向对象定义的那几个）。 */
export type JobPayloadSection =
${sections.map(([field]) => `  | ${JSON.stringify(field)}`).join("\n")};

/** \`definitions.${FIELD_LIST_TARGET.root}.properties\` 的键。 */
export const CREATE_JOB_TOP_LEVEL_FIELDS: readonly string[] = [
${renderFieldList(topLevel, 2)}
];

/** 每段对应定义的 \`properties\` 键。 */
export const CREATE_JOB_SECTION_FIELDS: Readonly<
  Record<JobPayloadSection, readonly string[]>
> = {
${sections.map(([field, definitionName]) => (
  `  ${field}: [\n${renderFieldList(closedFieldNames(schema, definitionName), 4)}\n  ],`
)).join("\n")}
};
`;

  if (CHECK_ONLY) {
    let current = "";
    try {
      current = await readFile(outputPath, "utf8");
    } catch {}
    if (normalizeLineEndings(current) !== generated) {
      throw new Error(
        `${FIELD_LIST_TARGET.output} is stale; run npm run generate --workspace @retainpdf/contracts`,
      );
    }
    return;
  }

  await writeFile(outputPath, generated, "utf8");
}

async function generateTarget(target) {
  const inputPath = resolve(PACKAGE_ROOT, target.input);
  const outputPath = resolve(PACKAGE_ROOT, target.output);
  const schema = JSON.parse(await readFile(inputPath, "utf8"));
  const endpointDefinitionNames = Array.from(new Set(
    (schema.endpoints || []).flatMap((endpoint) => (
      [endpoint.input, endpoint.query, endpoint.output]
        .filter((name) => typeof name === "string" && Object.hasOwn(schema.definitions, name))
    )),
  )).sort();
  assert.ok(endpointDefinitionNames.length > 0, `${target.input} has no endpoint DTO definitions`);
  const generationSchema = {
    $schema: schema.$schema,
    title: target.rootName,
    description: `Endpoint input, query, and output DTOs published by ${target.input}.`,
    oneOf: endpointDefinitionNames.map((name) => ({ $ref: `#/definitions/${name}` })),
    definitions: schema.definitions,
  };
  const generated = normalizeLineEndings(
    await compile(generationSchema, target.rootName, GENERATOR_OPTIONS),
  );

  if (CHECK_ONLY) {
    let current = "";
    try {
      current = await readFile(outputPath, "utf8");
    } catch {}
    if (normalizeLineEndings(current) !== generated) {
      throw new Error(
        `${target.output} is stale; run npm run generate --workspace @retainpdf/contracts`,
      );
    }
    return;
  }

  await writeFile(outputPath, generated, "utf8");
}

await Promise.all([...TARGETS.map(generateTarget), generateFieldList()]);
console.log(CHECK_ONLY ? "generated DTOs are current" : "generated DTOs updated");
