import assert from "node:assert/strict";
import { readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { compile } from "json-schema-to-typescript";

const PACKAGE_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const CHECK_ONLY = process.argv.includes("--check");
const TARGETS = [
  {
    input: "job-status.v1.schema.json",
    output: "src/job-status.ts",
    rootName: "JobStatusSchema",
  },
  {
    input: "library-books.v1.schema.json",
    output: "src/library-books.ts",
    rootName: "LibraryBooksSchema",
  },
];

const GENERATOR_OPTIONS = {
  additionalProperties: false,
  bannerComment: [
    "/* eslint-disable */",
    "/**",
    " * Generated by scripts/generate-types.mjs.",
    " * Do not edit by hand; update the source schema and run npm run generate.",
    " */",
  ].join("\n"),
  declareExternallyReferenced: true,
  enableConstEnums: false,
  format: true,
  ignoreMinAndMaxItems: false,
  strictIndexSignatures: false,
  style: {
    bracketSpacing: true,
    printWidth: 100,
    semi: true,
    singleQuote: false,
    tabWidth: 2,
    trailingComma: "all",
    useTabs: false,
  },
  unreachableDefinitions: true,
  unknownAny: false,
};

function normalizeLineEndings(value) {
  return value.replace(/\r\n?/g, "\n");
}

async function generateTarget(target) {
  const inputPath = resolve(PACKAGE_ROOT, target.input);
  const outputPath = resolve(PACKAGE_ROOT, target.output);
  const schema = JSON.parse(await readFile(inputPath, "utf8"));
  const endpointDefinitionNames = Array.from(new Set(
    (schema.endpoints || []).flatMap((endpoint) => (
      [endpoint.input, endpoint.query, endpoint.output]
        .filter((name) => typeof name === "string" && Object.hasOwn(schema.definitions, name))
    )),
  )).sort();
  assert.ok(endpointDefinitionNames.length > 0, `${target.input} has no endpoint DTO definitions`);
  const generationSchema = {
    $schema: schema.$schema,
    title: target.rootName,
    description: `Endpoint input, query, and output DTOs published by ${target.input}.`,
    oneOf: endpointDefinitionNames.map((name) => ({ $ref: `#/definitions/${name}` })),
    definitions: schema.definitions,
  };
  const generated = normalizeLineEndings(
    await compile(generationSchema, target.rootName, GENERATOR_OPTIONS),
  );

  if (CHECK_ONLY) {
    let current = "";
    try {
      current = await readFile(outputPath, "utf8");
    } catch {}
    if (normalizeLineEndings(current) !== generated) {
      throw new Error(
        `${target.output} is stale; run npm run generate --workspace @retainpdf/contracts`,
      );
    }
    return;
  }

  await writeFile(outputPath, generated, "utf8");
}

await Promise.all(TARGETS.map(generateTarget));
console.log(CHECK_ONLY ? "generated DTOs are current" : "generated DTOs updated");
