from __future__ import annotations


# Body font growth for translated paragraphs that visually underfill their OCR
# bbox. These values define the font-size side of the vertical slack budget.
BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER = 0.60
BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET = 0.80
BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_NO_SOURCE = 0.68
BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_SHORT = 0.72
BODY_UNDERFILLED_DENSITY_SAFE_MAX = 0.98
BODY_UNDERFILLED_RECOVERY_MAX_ITERATIONS = 6
BODY_UNDERFILLED_RECOVERY_FONT_STEP_PT = 0.28
BODY_UNDERFILLED_RECOVERY_LEADING_STEP_EM = 0.06
BODY_UNDERFILLED_UNIFIED_FONT_MAX_STEP_PT = 0.0
BODY_UNDERFILLED_FONT_GROW_DENSITY_TRIGGER = BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER
BODY_UNDERFILLED_FONT_GROW_DENSITY_LIMIT = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET
BODY_UNDERFILLED_FONT_GROW_MAX_PT = 1.15
BODY_UNDERFILLED_FONT_GROW_CONTEXT_BONUS_PT = 0.18
BODY_UNDERFILLED_FONT_GROW_PAGE_BONUS_PT = 0.16
BODY_UNDERFILLED_FONT_GROW_EXP_RATE = 1.55
BODY_UNDERFILLED_FONT_GROW_MAX_LINES = 8
BODY_UNDERFILLED_FONT_GROW_SHORT_LINE_BONUS = 0.04
BODY_UNDERFILLED_FONT_GROW_TALL_SLACK_BONUS = 0.08
BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_BONUS_PT = 0.18
BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_CAP_BONUS_PT = 0.16
BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_DENSITY_BONUS = 0.01
BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_RATIO_OFFSET = 1.25
BODY_UNDERFILLED_FONT_GROW_SOURCE_LINE_RATIO_RANGE = 2.75
BODY_UNDERFILLED_FONT_HARMONIZE_MAX_RATIO = 1.16
BODY_UNDERFILLED_FONT_GROW_MIN_LINES = 2
BODY_UNDERFILLED_FONT_GROW_MIN_HEIGHT_PT = 22.0
BODY_UNDERFILLED_FONT_GROW_SHORT_MAX_PT = 0.0
BODY_UNDERFILLED_FONT_GROW_LOW_FONT_SKIP_DELTA_PT = 0.20


# Page-level body font anchor. Long, stable body paragraphs act as anchors for
# short body blocks on the same page/column so font size does not jump sharply.
PAGE_BODY_FONT_ANCHOR_COUNT = 2
PAGE_BODY_FONT_ANCHOR_MIN_HEIGHT_PT = 42.0
PAGE_BODY_FONT_ANCHOR_MIN_LINES = 3
PAGE_BODY_FONT_ANCHOR_MIN_WIDTH_RATIO = 0.62
PAGE_BODY_FONT_ANCHOR_TARGET_MAX_RATIO = 1.12
PAGE_BODY_FONT_ANCHOR_TARGET_MAX_DELTA_PT = 1.15
PAGE_BODY_FONT_ANCHOR_APPLY_DENSITY_LIMIT = 1.20
PAGE_BODY_FONT_ANCHOR_SHORT_HEIGHT_RELAX_RATIO = 1.72
PAGE_BODY_FONT_ANCHOR_SHORT_HEIGHT_RELAX_MAX_EXTRA_PT = 14.0


# Body font unification. Prefer a conservative low-page anchor: one-line OCR
# boxes have no leading budget, so using large blocks as the target can make
# short/tight text jump upward and mislead density checks.
BODY_FONT_UNIFY_ANCHOR_COUNT = 2
BODY_FONT_UNIFY_ANCHOR_MIN_HEIGHT_PT = 30.0
BODY_FONT_UNIFY_ANCHOR_MIN_WIDTH_RATIO = 0.58
BODY_FONT_UNIFY_ANCHOR_MAX_DENSITY = 1.18
BODY_FONT_UNIFY_TARGET_QUANTILE = 0.25
BODY_FONT_UNIFY_EXTREME_SMALL_RATIO = 0.82
BODY_FONT_UNIFY_EXTREME_SMALL_DELTA_PT = 1.6
BODY_FONT_UNIFY_MIN_FILTERED_COUNT = 2
BODY_FONT_UNIFY_CANDIDATE_MIN_WIDTH_RATIO = 0.30
BODY_FONT_UNIFY_APPLY_TOLERANCE_PT = 0.08
BODY_FONT_UNIFY_MAX_SHRINK_PT = 1.25
BODY_FONT_UNIFY_GROW_DENSITY_LIMIT = 1.08
BODY_FONT_UNIFY_DIRECT_DENSE_MAX_LINES = 2
BODY_FONT_PRE_SMOOTH_MIN_LINES = 2
BODY_FONT_PRE_SMOOTH_MIN_HEIGHT_PT = 22.0


# Annotation font unification. Captions and footnotes follow the same low-anchor
# rule as body text, but their seed fonts are already smaller via role scales.
ANNOTATION_FONT_UNIFY_TARGET_QUANTILE = 0.25
ANNOTATION_FONT_UNIFY_EXTREME_SMALL_RATIO = 0.80
ANNOTATION_FONT_UNIFY_EXTREME_SMALL_DELTA_PT = 1.2
ANNOTATION_FONT_UNIFY_MIN_FILTERED_COUNT = 2
ANNOTATION_FONT_UNIFY_APPLY_TOLERANCE_PT = 0.06
ANNOTATION_FONT_UNIFY_MAX_SHRINK_PT = 0.9
CAPTION_BODY_FONT_CAP_RATIO = 0.88
CAPTION_FONT_UNIFY_TARGET_BONUS_PT = 0.0
CAPTION_FONT_UNIFY_MAX_GROW_PT = 0.0
FOOTNOTE_BODY_FONT_CAP_RATIO = 0.82
FOOTNOTE_FONT_UNIFY_TARGET_BONUS_PT = 0.04
FOOTNOTE_FONT_UNIFY_MAX_GROW_PT = 0.08
ANNOTATION_UNDERFILLED_DENSITY_FLOOR_TRIGGER = BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER
ANNOTATION_UNDERFILLED_DENSITY_RECOVERY_TARGET = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET
ANNOTATION_UNDERFILLED_DENSITY_SAFE_MAX = BODY_UNDERFILLED_DENSITY_SAFE_MAX
ANNOTATION_UNDERFILLED_RECOVERY_MAX_ITERATIONS = 5
CAPTION_UNDERFILLED_RECOVERY_FONT_STEP_PT = 0.08
CAPTION_UNDERFILLED_RECOVERY_LEADING_STEP_EM = 0.025
CAPTION_UNDERFILLED_RECOVERY_LEADING_CAP_EM = 0.68
FOOTNOTE_UNDERFILLED_RECOVERY_FONT_STEP_PT = 0.12
FOOTNOTE_UNDERFILLED_RECOVERY_LEADING_STEP_EM = 0.025
FOOTNOTE_UNDERFILLED_RECOVERY_LEADING_CAP_EM = 0.66


# Body leading recovery. The solver spends remaining vertical slack on line
# spacing after font growth, using source line count/pitch as soft signals.
BODY_COMFORT_LEADING_MIN = 0.56
BODY_COMFORT_LEADING_DENSITY_MAX = 0.985
BODY_COMFORT_DENSITY_FLOOR_TRIGGER = BODY_UNDERFILLED_DENSITY_FLOOR_TRIGGER
BODY_COMFORT_DENSITY_RECOVERY_TARGET = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET
BODY_COMFORT_DENSITY_RECOVERY_TARGET_NO_SOURCE = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_NO_SOURCE
BODY_COMFORT_DENSITY_RECOVERY_TARGET_SHORT = BODY_UNDERFILLED_DENSITY_RECOVERY_TARGET_SHORT
BODY_COMFORT_BASE_FILL = 0.70
BODY_COMFORT_TARGET_FILL_MAX = 0.90
BODY_COMFORT_LOW_SOURCE_LINE_COUNT_MAX = 5
BODY_COMFORT_LOW_SOURCE_LINE_TARGET_FILL_MAX = 0.78
BODY_COMFORT_LOW_SOURCE_LINE_LEADING_MAX = 0.70
BODY_COMFORT_LONG_LINE_THRESHOLD = 9
BODY_COMFORT_LONG_LEADING_MAX = 0.76
BODY_COMFORT_NO_SOURCE_LONG_LEADING_MAX = 0.74
BODY_COMFORT_SOURCE_LINE_LEADING_MAX = 1.02
BODY_COMFORT_SOLVER_MAX_ITERATIONS = 6
BODY_COMFORT_SOLVER_DENSITY_TOLERANCE = 0.002
BODY_COMFORT_SOLVER_MIN_BRACKET_WIDTH = 0.005
BODY_COMFORT_SOLVER_EXTRAPOLATION_MIN_FRACTION = 0.12
BODY_COMFORT_SOLVER_EXTRAPOLATION_MAX_FRACTION = 0.88
BODY_COMFORT_SLACK_NORMALIZER = 0.38
BODY_COMFORT_SOURCE_LINE_RATIO_OFFSET = 1.0
BODY_COMFORT_SOURCE_LINE_RATIO_MAX_GAP = 4.0
BODY_COMFORT_SOURCE_LEADING_MAX_GAP = 1.0
BODY_COMFORT_LINE_COUNT_BASE = 2.0
BODY_COMFORT_LINE_COUNT_NORMALIZER = 12.0
BODY_COMFORT_SLACK_GAIN_MAX = 0.08
BODY_COMFORT_SOURCE_LINE_GAIN_MAX = 0.12
BODY_COMFORT_SOURCE_PITCH_GAIN_MAX = 0.05
BODY_COMFORT_MULTI_LINE_GAIN_MAX = 0.10
BODY_COMFORT_FONT_GROWTH_GAIN_MAX = 0.03
BODY_COMFORT_FONT_GROWTH_MIN_LEADING_GAIN_MAX = 0.12
BODY_COMFORT_FONT_GROWTH_MIN_LEADING_RATE = 1.8
BODY_COMFORT_LEADING_GROWTH_BASE_MAX = 0.10
BODY_COMFORT_LEADING_GROWTH_SOURCE_MAX = 0.28
BODY_COMFORT_LEADING_GROWTH_LONG_TEXT_MAX = 0.08
BODY_COMFORT_LEADING_FONT_SPEND_PENALTY_MAX = 0.20
BODY_COMFORT_LEADING_GROWTH_MIN_AFTER_FONT_GROWTH = 0.04
BODY_COMFORT_PAGE_BASELINE_DENSITY_WEIGHT = 0.10
BODY_COMFORT_PAGE_BASELINE_MAX_DENSITY_DELTA = 0.20
BODY_COMFORT_SLACK_RESPONSE_RATE = 2.0
BODY_COMFORT_MULTI_LINE_WEIGHT_RATE = 0.42
BODY_COMFORT_SOURCE_LINE_RESPONSE_RATE = 0.78
BODY_COMFORT_SOURCE_LINE_VOLUME_BASE = 6.0
BODY_COMFORT_SOURCE_LINE_VOLUME_RESPONSE_RATE = 0.45
BODY_COMFORT_SOURCE_PITCH_RESPONSE_RATE = 3.2
BODY_COMFORT_LINE_COUNT_RESPONSE_RATE = 2.1
BODY_COMFORT_LONG_LINE_CAP_RESPONSE_RATE = 0.38
BODY_COMFORT_SOURCE_LINE_CAP_RESPONSE_RATE = 0.7
BODY_COMFORT_SOURCE_PITCH_CAP_RESPONSE_RATE = 1.1
BODY_COMFORT_FONT_GROWTH_NORMALIZER_PT = 1.2


# Tall OCR bboxes often include source paragraph slack rather than usable text
# height. Use an effective height for density decisions so body rhythm remains
# closer to the page/book font target instead of chasing excessive whitespace.
BODY_TALL_BBOX_MIN_LINES = 3
BODY_TALL_BBOX_MIN_HEIGHT_PT = 35.0
BODY_TALL_BBOX_HEIGHT_RATIO_TRIGGER = 1.8
BODY_TALL_BBOX_PAGE_RATIO_MULTIPLIER = 1.35
BODY_TALL_BBOX_EFFECTIVE_NATURAL_MULTIPLIER = 1.45
BODY_TALL_BBOX_EFFECTIVE_MIN_ORIGINAL_RATIO = 0.58


# Adjacent collision protection. Once body font unification has selected a page
# body font, collision handling should not break that rhythm with a second font
# fit pass. It may only compress leading.
BODY_COLLISION_UNIFIED_MIN_LEADING_EM = 0.52
BODY_COLLISION_UNIFIED_FONT_TOLERANCE_PT = 0.08
