from __future__ import annotations


BACKGROUND_PATCH_LIGHT_BG_MEDIAN_MIN = 245
BACKGROUND_PATCH_LIGHT_BG_P90_MIN = 250
BACKGROUND_PATCH_TEXT_CONTAMINATION_DARK_VALUE = 220
BACKGROUND_PATCH_TEXT_CONTAMINATION_DARK_RATIO = 0.015

BACKGROUND_COVER_SAMPLE_MARGIN_PT = 6.0
BACKGROUND_COVER_SAMPLE_SCALE = 2.0
BACKGROUND_COVER_MIN_SAMPLE_PIXELS = 24
BACKGROUND_COVER_MAX_SAMPLE_PIXELS = 4096
BACKGROUND_COVER_COMPLEXITY_BRIGHTNESS_SPREAD = 72

BACKGROUND_FILL_DOMINANT_BIN_SIZE = 8
BACKGROUND_FILL_DOMINANT_MIN_RATIO = 0.35
BACKGROUND_FILL_NONWHITE_MAX_CHANNEL = 0.98

BACKGROUND_CLIP_SAMPLER_MIN_RECTS = 8
BACKGROUND_CLIP_SAMPLER_MAX_PAGE_AREA_RATIO = 0.35
BACKGROUND_CLIP_SAMPLER_EXTRA_MARGIN_PT = 18.0
BACKGROUND_FULL_PAGE_SAMPLER_MIN_RECTS = 24
