export const state = {
  timer: null,
  elapsedTimer: null,
  currentJobId: "",
  currentJobSnapshot: null,
  currentJobManifest: null,
  currentJobStartedAt: "",
  currentJobFinishedAt: "",
  uploadId: "",
  uploadedFileName: "",
  uploadedPageCount: 0,
  uploadedBytes: 0,
  appliedPageRange: "",
  recentJobsOffset: 0,
  recentJobsHasMore: true,
  recentJobsDate: "",
  recentJobsItems: [],
  validatedMineruToken: "",
  mineruValidationStatus: "",
  developerConfig: {},
  desktopMode: false,
  desktopConfigured: false,
};
