export const DEFAULT_MODE = "sci";
export const DEFAULT_LANGUAGE = "ch";
export const DEFAULT_RULE_PROFILE = "general_sci";
export const DEFAULT_RENDER_MODE = "auto";
export const DEFAULT_TYPST_FONT_FAMILY = "Source Han Serif SC";
export const DEFAULT_PDF_COMPRESS_DPI = 0;
export const DEFAULT_TRANSLATED_PDF_NAME = "";
export const DEFAULT_BODY_FONT_SIZE_FACTOR = 0.95;
export const DEFAULT_BODY_LEADING_FACTOR = 1.08;
export const DEFAULT_INNER_BBOX_SHRINK_X = 0;
export const DEFAULT_INNER_BBOX_SHRINK_Y = 0;
export const DEFAULT_INNER_BBOX_DENSE_SHRINK_X = 0;
export const DEFAULT_INNER_BBOX_DENSE_SHRINK_Y = 0;
export const DEFAULT_FONT_UNIFY_MODE = "role_min";
export const DEFAULT_WORKERS = 50;
// 批翻译默认口径与 Python 引擎(TranslationExecutionRequest.batch_size=8)对齐:
// batch=1 会把每块拆成独立请求,批处理队列与批内上下文完全失效。
export const DEFAULT_BATCH_SIZE = 8;
export const DEFAULT_CLASSIFY_BATCH_SIZE = 12;
export const DEFAULT_COMPILE_WORKERS = 8;
export const DEFAULT_TIMEOUT_SECONDS = 1800;
