import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

const manifest = JSON.parse(readFileSync(resolve("package.json"), "utf8"));
const generatedCreateJob = readFileSync(resolve("src/create-job.ts"), "utf8");
const generatedCreateJobFields = readFileSync(resolve("src/create-job-fields.ts"), "utf8");
const generatedJobStatus = readFileSync(resolve("src/job-status.ts"), "utf8");
const generatedJobEvents = readFileSync(resolve("src/job-events.ts"), "utf8");
const generatedLibraryBooks = readFileSync(resolve("src/library-books.ts"), "utf8");
const generatedReaderData = readFileSync(resolve("src/reader-data.ts"), "utf8");
const RAW_SCHEMA_EXPORTS = [
  "./ai-ask.v1.schema.json",
  "./agent-calculation.v1.schema.json",
  "./ai-conversations.v1.schema.json",
  "./create-job.v1.schema.json",
  "./job-status.v1.schema.json",
  "./job-events.v2.schema.json",
  "./jobs-control.v1.schema.json",
  "./library-books.v1.schema.json",
  "./pipeline-stdout.v1.schema.json",
  "./public-document-operation.v1.schema.json",
  "./reader-data.v1.schema.json",
  "./runtime-config.v1.schema.json",
];

test("package exposes only explicit DTO and raw schema subpaths", () => {
  assert.deepEqual(
    Object.keys(manifest.exports).sort(),
    [
      "./create-job",
      "./create-job-fields",
      "./job-status",
      "./job-events",
      "./library-books",
      "./reader-data",
      ...RAW_SCHEMA_EXPORTS,
    ].sort(),
  );
  assert.equal(Object.hasOwn(manifest.exports, "."), false);
  assert.equal(Object.keys(manifest.exports).some((key) => key.includes("*")), false);
});

// `./create-job-fields` 是包里唯一一个导出**运行期值**的子路径：其余子路径的 dist/*.js
// 都是 `export {}`（类型在运行期不存在）。mock 层要模拟后端的 deny_unknown_fields，
// 需要的正是一份运行期能读的字段名白名单；以前那份是手抄在 frontend/web 里的。
// 它由 scripts/generate-types.mjs 从 create-job.v1.schema.json 生成，
// `npm run generate:check`（本 npm test 的第一步）保证它不落后于 schema。
test("create-job field lists are generated values, not hand-written ones", () => {
  assert.match(generatedCreateJobFields, /Generated by scripts\/generate-types\.mjs/);
  assert.match(
    generatedCreateJobFields,
    /export const CREATE_JOB_TOP_LEVEL_FIELDS: readonly string\[\] = \[/,
  );
  assert.match(
    generatedCreateJobFields,
    /export const CREATE_JOB_SECTION_FIELDS: Readonly<\n\s*Record<JobPayloadSection, readonly string\[\]>\n>/,
  );
  // 五个段一个都不能少：少一个，mock 就会对那一段完全放行。
  for (const section of ["source", "ocr", "translation", "render", "runtime"]) {
    assert.match(generatedCreateJobFields, new RegExp(`^  ${section}: \\[$`, "m"));
  }
});

test("package has no runtime dependencies", () => {
  assert.deepEqual(manifest.dependencies, {});
});

test("generated DTO entries expose the stable consumer type names", () => {
  for (const typeName of [
    "ArtifactDisplayItemView",
    "BookSummaryView",
    "JobDetailView",
    "JobFailureInfo",
    "JobListItemView",
    "JobListView",
    "JobRuntimeInfo",
    "NormalizationSummaryView",
    "OcrProviderDiagnostics",
    "PublicResolvedJobSpec",
  ]) {
    assert.match(generatedJobStatus, new RegExp(`export (?:interface|type) ${typeName}\\b`));
  }
  for (const typeName of [
    "CreateJobInput",
    "GlossaryEntryInput",
    "JobSourceInput",
    "OcrInput",
    "RenderInput",
    "RuntimeInput",
    "TranslationInput",
  ]) {
    assert.match(generatedCreateJob, new RegExp(`export (?:interface|type) ${typeName}\\b`));
  }
  for (const typeName of [
    "JobEventListView",
    "JobEventRecord",
    "ListJobEventsQuery",
  ]) {
    assert.match(generatedJobEvents, new RegExp(`export (?:interface|type) ${typeName}\\b`));
  }
  for (const typeName of [
    "ArtifactDisplayItemView",
    "JobListItemView",
    "JobListView",
    "LibraryBookDetailView",
    "LibraryBookListItemView",
    "LibraryBookListView",
  ]) {
    assert.match(generatedLibraryBooks, new RegExp(`export (?:interface|type) ${typeName}\\b`));
  }
});

test("generated job DTOs keep request and event records structurally typed", () => {
  assert.match(generatedJobStatus, /request_payload: PublicResolvedJobSpec;/);
  assert.match(generatedJobEvents, /items: JobEventRecord\[\];/);
  assert.doesNotMatch(generatedJobStatus, /request_payload: \{\};/);
  assert.doesNotMatch(generatedJobStatus, /items: \{\}\[\];/);
  assert.doesNotMatch(generatedJobStatus, /\?: \{\} \| null;/);
});

test("generated Reader DTO entry exposes host-port read model types", () => {
  for (const typeName of [
    "LiveTranslationCommitEvent",
    "LiveTranslationLayout",
    "LiveTranslationPageSnapshot",
    "MarkdownDocumentView",
    "ReaderArtifactManifestView",
    "ReaderMetadataView",
    "ReaderRegionsView",
  ]) {
    assert.match(generatedReaderData, new RegExp(`export (?:interface|type) ${typeName}\\b`));
  }
  assert.doesNotMatch(generatedReaderData, /relative_path:/);
  assert.doesNotMatch(generatedReaderData, /provider_raw_dir:/);
  assert.doesNotMatch(generatedReaderData, /provider_zip:/);
  assert.doesNotMatch(generatedReaderData, /provider_summary_json:/);
});
