from __future__ import annotations


HEAVY_VECTOR_PAGE_DRAWINGS_THRESHOLD = 5000
LOCAL_VECTOR_ITEM_DRAWINGS_THRESHOLD = 64
LOCAL_VECTOR_ITEM_AREA_RATIO_THRESHOLD = 0.15

WORD_REDACTION_PAD_X = 1.0
WORD_REDACTION_PAD_Y = 0.6
FORMULA_REDACTION_PAD_X = 1.8
FORMULA_REDACTION_PAD_Y = 1.2

COVER_SAMPLE_MARGIN_PT = 6.0
COVER_SAMPLE_SCALE = 2.0
COVER_MIN_SAMPLE_PIXELS = 24
COVER_COMPLEXITY_BRIGHTNESS_SPREAD = 72

MATH_INTRUSIVE_HEIGHT_RATIO = 2.2
MATH_INTRUSIVE_OVERLAP_AREA_MIN = 1.0

SPECIAL_MATH_FONT_MARKERS = (
    "pearsonmath",
    "mathematicalpi",
    "newcmmath",
    "stixmath",
    "cambria math",
    "latinmodernmath",
    "xitsmath",
    "math",
)
