from __future__ import annotations


BACKGROUND_PATCH_LIGHT_BG_MEDIAN_MIN = 245
BACKGROUND_PATCH_LIGHT_BG_P90_MIN = 250
BACKGROUND_PATCH_TEXT_CONTAMINATION_DARK_VALUE = 220
BACKGROUND_PATCH_TEXT_CONTAMINATION_DARK_RATIO = 0.015

BACKGROUND_COVER_SAMPLE_MARGIN_PT = 6.0
BACKGROUND_COVER_SAMPLE_SCALE = 2.0
BACKGROUND_COVER_MIN_SAMPLE_PIXELS = 24
BACKGROUND_COVER_COMPLEXITY_BRIGHTNESS_SPREAD = 72
