from __future__ import annotations


BBOX_TEXT_STRIP_CONTENT_STREAM_SIZE_THRESHOLD = 1_000_000

STRIP_SEGMENT_PAD_X_PT = 1.0
STRIP_SEGMENT_PAD_Y_PT = 1.0
FORMULA_SPLIT_SEGMENT_PAD_X_PT = 1.0
FORMULA_SPLIT_SEGMENT_PAD_Y_PT = 0.0
