use serde::Serialize;

use super::common::WorkflowKind;
use super::input::{
    GlossaryEntryInput, RenderInput, ResolvedJobSpec, ResolvedSourceSpec, RuntimeInput,
};

#[derive(Debug, Serialize, Clone)]
pub struct PublicResolvedJobSpec {
    pub workflow: WorkflowKind,
    pub job_id: String,
    pub source: ResolvedSourceSpec,
    pub ocr: PublicOcrInput,
    pub translation: PublicTranslationInput,
    pub render: RenderInput,
    pub runtime: RuntimeInput,
}

#[derive(Debug, Serialize, Clone)]
pub struct PublicOcrInput {
    pub provider: String,
    pub mineru_token: String,
    pub mineru_token_configured: bool,
    pub model_version: String,
    pub paddle_token: String,
    pub paddle_token_configured: bool,
    pub paddle_api_url: String,
    pub paddle_model: String,
    pub is_ocr: bool,
    pub disable_formula: bool,
    pub disable_table: bool,
    pub language: String,
    pub page_ranges: String,
    pub data_id: String,
    pub no_cache: bool,
    pub cache_tolerance: i64,
    pub extra_formats: String,
    pub poll_interval: i64,
    pub poll_timeout: i64,
}

#[derive(Debug, Serialize, Clone)]
pub struct PublicTranslationInput {
    pub mode: String,
    pub math_mode: String,
    pub skip_title_translation: bool,
    pub classify_batch_size: i64,
    pub rule_profile_name: String,
    pub custom_rules_text: String,
    pub glossary_id: String,
    pub glossary_name: String,
    pub glossary_resource_entry_count: i64,
    pub glossary_inline_entry_count: i64,
    pub glossary_overridden_entry_count: i64,
    pub glossary_entries: Vec<GlossaryEntryInput>,
    pub context_mode: String,
    pub glossary_mode: String,
    pub memory_mode: String,
    pub api_key: String,
    pub api_key_configured: bool,
    pub model: String,
    pub base_url: String,
    pub start_page: i64,
    pub end_page: i64,
    pub batch_size: i64,
    pub workers: i64,
    pub target_language_name: String,
}

pub fn public_request_payload(spec: &ResolvedJobSpec) -> PublicResolvedJobSpec {
    PublicResolvedJobSpec {
        workflow: spec.workflow.clone(),
        job_id: spec.job_id.clone(),
        source: spec.source.clone(),
        ocr: PublicOcrInput {
            provider: spec.ocr.provider.clone(),
            mineru_token: String::new(),
            mineru_token_configured: !spec.ocr.mineru_token.trim().is_empty(),
            model_version: spec.ocr.model_version.clone(),
            paddle_token: String::new(),
            paddle_token_configured: !spec.ocr.paddle_token.trim().is_empty(),
            paddle_api_url: spec.ocr.paddle_api_url.clone(),
            paddle_model: spec.ocr.paddle_model.clone(),
            is_ocr: spec.ocr.is_ocr,
            disable_formula: spec.ocr.disable_formula,
            disable_table: spec.ocr.disable_table,
            language: spec.ocr.language.clone(),
            page_ranges: spec.ocr.page_ranges.clone(),
            data_id: spec.ocr.data_id.clone(),
            no_cache: spec.ocr.no_cache,
            cache_tolerance: spec.ocr.cache_tolerance,
            extra_formats: spec.ocr.extra_formats.clone(),
            poll_interval: spec.ocr.poll_interval,
            poll_timeout: spec.ocr.poll_timeout,
        },
        translation: PublicTranslationInput {
            mode: spec.translation.mode.clone(),
            math_mode: spec.translation.math_mode.clone(),
            skip_title_translation: spec.translation.skip_title_translation,
            classify_batch_size: spec.translation.classify_batch_size,
            rule_profile_name: spec.translation.rule_profile_name.clone(),
            custom_rules_text: spec.translation.custom_rules_text.clone(),
            glossary_id: spec.translation.glossary_id.clone(),
            glossary_name: spec.translation.glossary_name.clone(),
            glossary_resource_entry_count: spec.translation.glossary_resource_entry_count,
            glossary_inline_entry_count: spec.translation.glossary_inline_entry_count,
            glossary_overridden_entry_count: spec.translation.glossary_overridden_entry_count,
            glossary_entries: spec.translation.glossary_entries.clone(),
            context_mode: spec.translation.context_mode.clone(),
            glossary_mode: spec.translation.glossary_mode.clone(),
            memory_mode: spec.translation.memory_mode.clone(),
            api_key: String::new(),
            api_key_configured: !spec.translation.api_key.trim().is_empty(),
            model: spec.translation.model.clone(),
            base_url: spec.translation.base_url.clone(),
            start_page: spec.translation.start_page,
            end_page: spec.translation.end_page,
            batch_size: spec.translation.batch_size,
            workers: spec.translation.workers,
            target_language_name: spec.translation.target_language_name.clone(),
        },
        render: spec.render.clone(),
        runtime: spec.runtime.clone(),
    }
}
