from foundation.config.fonts import DEFAULT_FONT_PATH
from foundation.config.fonts import DEFAULT_FONT_SIZE
from foundation.config.fonts import MIN_FONT_SIZE
from foundation.config.fonts import TYPST_DEFAULT_FONT_FAMILY
from foundation.config.layout import BODY_FONT_SIZE_FACTOR
from foundation.config.layout import BODY_LEADING_FACTOR
from foundation.config.layout import INNER_BBOX_DENSE_SHRINK_X
from foundation.config.layout import INNER_BBOX_DENSE_SHRINK_Y
from foundation.config.layout import INNER_BBOX_SHRINK_X
from foundation.config.layout import INNER_BBOX_SHRINK_Y
from foundation.config.layout import apply_layout_tuning
from foundation.config.paths import DATA_DIR
from foundation.config.paths import OUTPUT_DIR
from foundation.config.paths import ROOT_DIR
from foundation.config.paths import SOURCE_JSON
from foundation.config.paths import SOURCE_PDF
from foundation.config.paths import TRANSLATION_UNIT_CACHE_DIR
from foundation.config.paths import TRANSLATIONS_DIR
from foundation.config.runtime import DEFAULT_OUTPUT_NAME
from foundation.config.runtime import DEFAULT_PAGE_INDEX
from foundation.config.runtime import DEFAULT_PDF_COMPRESS_DPI

