/* eslint-disable */
/**
 * Generated by scripts/generate-types.mjs.
 * Do not edit by hand; update the source schema and run npm run generate.
 */

/**
 * Endpoint input, query, and output DTOs published by create-job.v1.schema.json.
 */
export type CreateJobSchema = CreateJobInput;
export type WorkflowKind = "book" | "ocr" | "translate" | "render";
/**
 * 可安全跨线传输的任意 JSON 值；用于 provider 扩展 options。
 */
export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };

/**
 * models/input/request.rs :: CreateJobInput。六个顶层字段全部可省（Rust 侧都是 #[serde(default)]），但**不认识的字段一律 400**。
 */
export interface CreateJobInput {
  workflow?: WorkflowKind;
  source?: JobSourceInput;
  ocr?: OcrInput;
  translation?: TranslationInput;
  render?: RenderInput;
  runtime?: RuntimeInput;
}
/**
 * models/input/source.rs :: JobSourceInput。三选一：上传件 / 外部 URL / 复用既有任务产物。
 */
export interface JobSourceInput {
  upload_id?: string;
  source_url?: string;
  artifact_job_id?: string;
}
/**
 * models/input/ocr.rs :: OcrInput。凭据可以用 credential_ref 引用，也可以内联 mineru_token / paddle_token。
 */
export interface OcrInput {
  provider?: string;
  credential_ref?: string;
  mineru_token?: string;
  model_version?: string;
  paddle_token?: string;
  paddle_api_url?: string;
  paddle_model?: string;
  is_ocr?: boolean;
  disable_formula?: boolean;
  disable_table?: boolean;
  language?: string;
  page_ranges?: string;
  data_id?: string;
  no_cache?: boolean;
  cache_tolerance?: number;
  extra_formats?: string;
  poll_interval?: number;
  poll_timeout?: number;
  options?: {
    [k: string]: JsonValue;
  };
}
/**
 * models/input/translation.rs :: TranslationInput。与响应侧的 PublicTranslationInput 的差别：这里 api_key 可以带明文，且**没有** api_key_configured —— 那个字段只存在于脱敏后的响应里，带上就会被 deny_unknown_fields 拒掉。
 */
export interface TranslationInput {
  execution_connection?: ModelConnection;
  mode?: string;
  /**
   * TRANSLATION_MATH_MODES
   */
  math_mode?: "direct_typst" | "placeholder";
  skip_title_translation?: boolean;
  classify_batch_size?: number;
  rule_profile_name?: string;
  custom_rules_text?: string;
  glossary_id?: string;
  glossary_name?: string;
  glossary_resource_entry_count?: number;
  glossary_inline_entry_count?: number;
  glossary_overridden_entry_count?: number;
  glossary_entries?: GlossaryEntryInput[];
  /**
   * TRANSLATION_CONTEXT_MODES
   */
  context_mode?: "needed" | "all" | "off";
  /**
   * TRANSLATION_GLOSSARY_MODES
   */
  glossary_mode?: "matched" | "all" | "off";
  /**
   * TRANSLATION_MEMORY_MODES
   */
  memory_mode?: "matched" | "broad" | "off";
  api_key?: string;
  credential_ref?: string;
  model?: string;
  base_url?: string;
  start_page?: number;
  end_page?: number;
  /**
   * 显式的一基页码；空数组保持 start_page/end_page 的旧语义。
   */
  page_ranges?: number[];
  batch_size?: number;
  workers?: number;
  accepted_ambiguous_request_risk?: boolean;
}
/**
 * model_connection.rs :: ModelConnection。不含明文密钥，只带 credential_ref。
 */
export interface ModelConnection {
  id: string;
  revision: number;
  provider: "qwen" | "deepseek" | "openai_compatible";
  base_url: string;
  model: string;
  credential_ref: string;
  concurrency: number;
  thinking?: "auto" | "off" | "on";
  stream?: boolean | null;
  allow_private_endpoint?: boolean;
  deadlines?: {
    queue_ms: number;
    connect_ms: number;
    idle_ms: number;
    total_ms: number;
  };
}
/**
 * models/input/translation.rs :: GlossaryEntryInput
 */
export interface GlossaryEntryInput {
  source?: string;
  target?: string;
  note?: string;
  level?: string;
  match_mode?: string;
  context?: string;
}
/**
 * models/input/render.rs :: RenderInput。默认值的权威来源是 backend/api/RENDER_OPTIONS_CONTRACT.md。
 */
export interface RenderInput {
  render_mode?: string;
  compile_workers?: number;
  typst_font_family?: string;
  pdf_compress_dpi?: number;
  translated_pdf_name?: string;
  body_font_size_factor?: number;
  body_leading_factor?: number;
  inner_bbox_shrink_x?: number;
  inner_bbox_shrink_y?: number;
  inner_bbox_dense_shrink_x?: number;
  inner_bbox_dense_shrink_y?: number;
  font_unify_mode?: string;
  /**
   * SOURCE_CLEANUP_STRATEGIES
   */
  source_cleanup_strategy?:
    "pikepdf_text_strip" | "bbox_text_strip" | "legacy" | "redact_restore_formulas";
}
/**
 * models/input/runtime.rs :: RuntimeInput
 */
export interface RuntimeInput {
  job_id?: string;
  timeout_seconds?: number;
  /**
   * 空闲检测：多久没有 stdout 输出就判定 worker 卡死（秒）。0 表示关闭，也是默认值。与 timeout_seconds 相互独立——后者是整段执行的上限，要按最坏情况给。
   */
  no_output_timeout_seconds?: number;
  /**
   * 内部执行策略：文档级翻译接口在翻译后还要产出渲染候选。公共 translate 工作流通常翻完即止。
   */
  render_after_translation?: boolean;
}
