/* eslint-disable */
/**
 * Generated by scripts/generate-types.mjs.
 * Do not edit by hand; update the source schema and run npm run generate.
 */

/**
 * Endpoint input, query, and output DTOs published by job-status.v1.schema.json.
 */
export type JobStatusSchema =
  JobDetailView | JobEventListView | JobListView | ListJobEventsQuery | ListJobsQuery;
export type WorkflowKind = "book" | "ocr" | "translate" | "render";
/**
 * crate::models::common::JobStatusKind
 */
export type JobStatusKind = "queued" | "running" | "succeeded" | "failed" | "canceled";
/**
 * 可安全跨线传输的任意 JSON 值；用于 provider 扩展 options 与事件 payload。
 */
export type JsonValue =
  null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue };
export type JobStageStateView =
  "reused" | "queued" | "pending" | "in_progress" | "completed" | "failed" | "skipped";
export type OcrProviderKind = "mineru" | "paddle" | "local" | "unknown";
export type OcrTaskState =
  "queued" | "waiting_upload" | "running" | "converting" | "succeeded" | "failed" | "unknown";

/**
 * job_types.rs :: JobDetailView。关键重复字段：job_id, workflow, status, stage_snapshot(含 progress), cover_url(经 book_summary.cover_url) 均上锁。
 */
export interface JobDetailView {
  job_id: string;
  workflow: WorkflowKind;
  status: JobStatusKind;
  ocr_reused: boolean;
  source_artifact_job_id: string | null;
  request_payload: PublicResolvedJobSpec;
  trace_id?: string | null;
  provider_trace_id?: string | null;
  stage_snapshot?: JobStageSnapshotView | null;
  background_snapshots?: JobStageSnapshotView[];
  stages: JobStagesView;
  timestamps: JobTimestampsView;
  links: JobLinksView;
  actions: JobActionsView;
  artifacts: ArtifactLinksView;
  artifacts_display: ArtifactDisplayItemView[];
  book_summary: BookSummaryView;
  contracts: JobContractsView;
  ocr_job?: OcrJobSummaryView | null;
  ocr_provider_diagnostics?: OcrProviderDiagnostics | null;
  runtime?: JobRuntimeInfo | null;
  failure?: JobFailureInfo | null;
  error?: string | null;
  failure_diagnostic?: JobFailureDiagnosticView | null;
  normalization_summary?: NormalizationSummaryView | null;
  glossary_summary?: GlossaryUsageSummaryView | null;
  invocation?: InvocationSummaryView | null;
  translation_request_recovery?: TranslationRequestRecoveryView | null;
  log_tail: string[];
}
/**
 * public_contract.rs :: PublicResolvedJobSpec。JobDetailView.request_payload 的脱敏线格式。
 */
export interface PublicResolvedJobSpec {
  workflow: WorkflowKind;
  job_id: string;
  source: ResolvedSourceSpec;
  ocr: PublicOcrInput;
  translation: PublicTranslationInput;
  render: RenderInput;
  runtime: RuntimeInput;
}
/**
 * public_contract.rs :: PublicResolvedJobSpec.source
 */
export interface ResolvedSourceSpec {
  upload_id: string;
  source_url: string;
  artifact_job_id: string;
}
/**
 * public_contract.rs :: PublicOcrInput。凭据正文恒为空，仅暴露 configured 标记。
 */
export interface PublicOcrInput {
  provider: string;
  credential_ref: string;
  mineru_token: string;
  mineru_token_configured: boolean;
  model_version: string;
  paddle_token: string;
  paddle_token_configured: boolean;
  paddle_api_url: string;
  paddle_model: string;
  is_ocr: boolean;
  disable_formula: boolean;
  disable_table: boolean;
  language: string;
  page_ranges: string;
  data_id: string;
  no_cache: boolean;
  cache_tolerance: number;
  extra_formats: string;
  poll_interval: number;
  poll_timeout: number;
  options: {
    [k: string]: JsonValue;
  };
}
/**
 * public_contract.rs :: PublicTranslationInput。api_key 恒为空，仅暴露 configured 标记。
 */
export interface PublicTranslationInput {
  mode: string;
  math_mode: string;
  skip_title_translation: boolean;
  classify_batch_size: number;
  rule_profile_name: string;
  custom_rules_text: string;
  glossary_id: string;
  glossary_name: string;
  glossary_resource_entry_count: number;
  glossary_inline_entry_count: number;
  glossary_overridden_entry_count: number;
  glossary_entries: GlossaryEntryInput[];
  context_mode: string;
  glossary_mode: string;
  memory_mode: string;
  api_key: string;
  api_key_configured: boolean;
  credential_ref: string;
  model: string;
  base_url: string;
  start_page: number;
  end_page: number;
  page_ranges: number[];
  batch_size: number;
  workers: number;
  accepted_ambiguous_request_risk?: boolean;
  execution_connection?: ModelConnection;
}
export interface GlossaryEntryInput {
  source: string;
  target: string;
  note: string;
  level: string;
  match_mode: string;
  context: string;
}
export interface ModelConnection {
  id: string;
  revision: number;
  provider: "qwen" | "deepseek" | "openai_compatible";
  base_url: string;
  model: string;
  credential_ref: string;
  concurrency: number;
  thinking?: "auto" | "off" | "on";
  stream?: boolean | null;
  allow_private_endpoint?: boolean;
  deadlines?: {
    queue_ms: number;
    connect_ms: number;
    idle_ms: number;
    total_ms: number;
  };
}
export interface RenderInput {
  render_mode: string;
  compile_workers: number;
  typst_font_family: string;
  pdf_compress_dpi: number;
  translated_pdf_name: string;
  body_font_size_factor: number;
  body_leading_factor: number;
  inner_bbox_shrink_x: number;
  inner_bbox_shrink_y: number;
  inner_bbox_dense_shrink_x: number;
  inner_bbox_dense_shrink_y: number;
  font_unify_mode: string;
  source_cleanup_strategy: string;
}
export interface RuntimeInput {
  job_id: string;
  timeout_seconds: number;
  render_after_translation: boolean;
}
/**
 * job_types.rs :: JobStageSnapshotView。前端 adaptJobStageSnapshot / buildStageSnapshot 消费全部字段；lane=main|background。
 */
export interface JobStageSnapshotView {
  display_stage?: string | null;
  stage?: string | null;
  substage?: string | null;
  lane?: string | null;
  stage_detail?: string | null;
  progress: JobProgressView;
}
/**
 * common.rs :: JobProgressView。前端 progress_unit / progress_current / progress_total 均由此归一。
 */
export interface JobProgressView {
  /**
   * JobProgress.current，null=未知
   */
  current?: number | null;
  total?: number | null;
  percent?: number | null;
  /**
   * page|batch|step|percent，skip_serializing_if None
   */
  unit?: string | null;
}
export interface JobStagesView {
  ocr: JobStageRuntimeView;
  translation: JobStageRuntimeView;
  render: JobStageRuntimeView;
}
export interface JobStageRuntimeView {
  state: JobStageStateView;
  progress: JobProgressView;
}
export interface JobTimestampsView {
  created_at: string;
  updated_at: string;
  started_at?: string | null;
  finished_at?: string | null;
  duration_seconds?: number | null;
}
export interface JobLinksView {
  self_path: string;
  self_url: string;
  artifacts_path: string;
  artifacts_url: string;
  artifacts_manifest_path: string;
  artifacts_manifest_url: string;
  events_path: string;
  events_url: string;
  cancel_path: string;
  cancel_url: string;
}
export interface JobActionsView {
  open_job: ActionLinkView;
  open_artifacts: ActionLinkView;
  cancel: ActionLinkView;
  rerun: ActionLinkView;
  download_pdf: ActionLinkView;
  open_markdown: ActionLinkView;
  open_markdown_raw: ActionLinkView;
  download_bundle: ActionLinkView;
}
export interface ActionLinkView {
  enabled: boolean;
  method: string;
  path: string;
  url: string;
}
export interface ArtifactLinksView {
  pdf_ready: boolean;
  markdown_ready: boolean;
  bundle_ready: boolean;
  schema_version?: string | null;
  provider_raw_dir?: string | null;
  provider_zip?: string | null;
  provider_summary_json?: string | null;
  pdf_url: string;
  markdown_url: string;
  markdown_images_base_url: string;
  bundle_url: string;
  normalized_document_url: string;
  normalization_report_url: string;
  manifest_path: string;
  manifest_url: string;
  actions: JobActionsView;
  normalized_document: ResourceLinkView;
  normalization_report: ResourceLinkView;
  pdf: ResourceLinkView;
  markdown: MarkdownArtifactView;
  bundle: ResourceLinkView;
}
export interface ResourceLinkView {
  ready: boolean;
  path: string;
  url: string;
  method: string;
  content_type: string;
  file_name?: string | null;
  size_bytes?: number | null;
}
export interface MarkdownArtifactView {
  ready: boolean;
  json_path: string;
  json_url: string;
  raw_path: string;
  raw_url: string;
  images_base_path: string;
  images_base_url: string;
  file_name?: string | null;
  size_bytes?: number | null;
}
export interface ArtifactDisplayItemView {
  key: string;
  label: string;
  ready: boolean;
  kind: string;
  file_name?: string | null;
  size_bytes?: number | null;
  download_url?: string | null;
}
export interface BookSummaryView {
  title: string;
  authors?: string | null;
  page_count?: number | null;
  source_language?: string | null;
  target_language?: string | null;
  source_file_name?: string | null;
  cover_url?: string | null;
  /**
   * 前端常用，Rust ListItem 有，BookSummary 扩展补充
   */
  thumbnail_url?: string | null;
  file_size_bytes?: number | null;
}
export interface JobContractsView {
  schema_version: string;
  stages: JobStageContractView[];
}
export interface JobStageContractView {
  stage: string;
  ready: boolean;
  artifacts: JobStageContractArtifactView[];
}
export interface JobStageContractArtifactView {
  artifact_key: string;
  required: boolean;
  ready: boolean;
  relative_path?: string | null;
  detail?: string | null;
}
export interface OcrJobSummaryView {
  job_id: string;
  status?: JobStatusKind | null;
  trace_id?: string | null;
  provider_trace_id?: string | null;
  detail_path: string;
  detail_url: string;
}
export interface OcrProviderDiagnostics {
  provider: OcrProviderKind;
  capabilities: OcrProviderCapabilities | null;
  handle: OcrTaskHandle;
  last_status: OcrTaskStatus | null;
  last_error: OcrProviderErrorInfo | null;
  artifacts: OcrArtifactSet;
}
export interface OcrProviderCapabilities {
  supports_remote_url_submit: boolean;
  supports_local_file_upload: boolean;
  supports_polling: boolean;
  supports_download_bundle: boolean;
  supports_extra_formats: boolean;
  supports_formula_toggle: boolean;
  supports_table_toggle: boolean;
}
export interface OcrTaskHandle {
  batch_id: string | null;
  task_id: string | null;
  file_name: string | null;
}
export interface OcrTaskStatus {
  provider: OcrProviderKind;
  handle: OcrTaskHandle;
  state: OcrTaskState;
  raw_state: string | null;
  stage: string | null;
  detail: string | null;
  provider_message: string | null;
  trace_id: string | null;
}
export interface OcrProviderErrorInfo {
  category: string;
  provider_code: string | null;
  provider_message: string | null;
  operator_hint: string | null;
  trace_id: string | null;
  http_status: number | null;
}
export interface OcrArtifactSet {
  full_zip_url: string | null;
  provider_result_json: string | null;
  provider_bundle_zip: string | null;
  layout_json: string | null;
  normalized_document_json: string | null;
  normalization_report_json: string | null;
}
export interface JobRuntimeInfo {
  current_stage: string | null;
  stage_started_at: string | null;
  last_stage_transition_at: string | null;
  terminal_reason: string | null;
  last_error_at: string | null;
  total_elapsed_ms: number | null;
  active_stage_elapsed_ms: number | null;
  retry_count: number;
  last_retry_at: string | null;
  stage_history: JobStageTiming[];
  final_failure_category: string | null;
  final_failure_summary: string | null;
}
export interface JobStageTiming {
  stage: string;
  detail: string | null;
  enter_at: string;
  exit_at: string | null;
  duration_ms: number | null;
  terminal_status: JobStatusKind | null;
}
export interface JobFailureInfo {
  stage: string;
  category: string;
  code: string | null;
  failed_stage?: string;
  failure_code?: string;
  failure_category?: string;
  provider_stage?: string;
  provider_code?: string;
  summary: string;
  root_cause: string | null;
  retryable: boolean;
  upstream_host: string | null;
  provider: string | null;
  suggestion: string | null;
  last_log_line: string | null;
  raw_excerpt?: string;
  raw_error_excerpt: string | null;
  raw_diagnostic: JobRawDiagnostic | null;
  ai_diagnostic: JobAiDiagnostic | null;
}
export interface JobRawDiagnostic {
  structured_error_type: string | null;
  raw_exception_type: string | null;
  raw_exception_message: string | null;
  traceback: string | null;
}
export interface JobAiDiagnostic {
  summary: string;
  root_cause: string | null;
  suggestion: string | null;
  confidence: string | null;
  observed_signals: string[];
}
export interface JobFailureDiagnosticView {
  failed_stage: string;
  error_kind: string;
  summary: string;
  root_cause: string | null;
  retryable: boolean;
  upstream_host: string | null;
  suggestion: string | null;
  last_log_line: string | null;
}
export interface NormalizationSummaryView {
  provider: string;
  detected_provider: string;
  provider_was_explicit: boolean;
  pages_seen: number | null;
  blocks_seen: number | null;
  document_defaults: number;
  page_defaults: number;
  block_defaults: number;
  schema: string;
  schema_version: string;
  page_count: number | null;
  block_count: number | null;
}
export interface GlossaryUsageSummaryView {
  enabled: boolean;
  glossary_id: string;
  glossary_name: string;
  entry_count: number;
  resource_entry_count: number;
  inline_entry_count: number;
  overridden_entry_count: number;
  source_hit_entry_count: number;
  target_hit_entry_count: number;
  unused_entry_count: number;
  unapplied_source_hit_entry_count: number;
}
export interface InvocationSummaryView {
  stage: string;
  input_protocol: string;
  stage_spec_schema_version: string;
}
export interface TranslationRequestRecoveryView {
  status: "clean" | "ambiguous" | "corrupt" | "blocked" | "running" | "paused";
  journal_ready: boolean;
  unresolved_dispatches: number;
  active_ambiguous_request_keys: number;
  historical_ambiguous_request_keys: number;
  requires_confirmation: boolean;
  supported_retry_policies: ("block" | "accept_duplicate_risk")[];
  detail: string | null;
}
export interface JobEventListView {
  items: JobEventRecord[];
  limit: number;
  offset: number;
}
/**
 * translation.rs :: JobEventRecord 的公开序列化形状。payload 保留递归 JSON 类型，不再退化为 {}。
 */
export interface JobEventRecord {
  job_id: string;
  seq: number;
  ts: string;
  created_at?: string;
  level: string;
  lane: string | null;
  display_stage?: string;
  stage: string | null;
  substage: string | null;
  stage_detail: string | null;
  provider: string | null;
  provider_stage: string | null;
  event: string;
  event_type: string | null;
  raw_event_type: string | null;
  raw?: JobEventRawView;
  progress?: JobEventProgressView;
  message: string;
  retry_count: number | null;
  elapsed_ms: number | null;
  payload: JsonValue;
}
/**
 * 事件进入 API 归一化之前的来源追踪字段。
 */
export interface JobEventRawView {
  source_kind?: string;
  source_seq?: number;
  stage?: string;
  user_stage?: string;
  event_type?: string;
}
/**
 * translation.rs :: JobEventProgressView。字段为可选，因为未知进度可序列化为空对象。
 */
export interface JobEventProgressView {
  unit?: string;
  current?: number;
  total?: number;
  percent?: number;
}
export interface JobListView {
  items: JobListItemView[];
  invocation_summary: JobListInvocationSummaryView;
}
/**
 * job_types.rs :: JobListItemView — 列表卡用；关键字段 job_id / display_name / workflow / status / stage_snapshot / progress(经 stage_snapshot.progress) / cover_url 均在契约内。
 */
export interface JobListItemView {
  job_id: string;
  display_name: string;
  workflow: WorkflowKind;
  status: JobStatusKind;
  attempt: number;
  retry_count: number;
  last_retry_at: string | null;
  trace_id?: string | null;
  stage_snapshot: JobStageSnapshotView | null;
  background_snapshots: JobStageSnapshotView[];
  stages: JobStagesView;
  page_count?: number | null;
  source_file_name?: string | null;
  cover_url?: string | null;
  thumbnail_url?: string | null;
  output_pdf_ready: boolean;
  markdown_ready: boolean;
  bundle_ready: boolean;
  invocation?: InvocationSummaryView | null;
  created_at: string;
  updated_at: string;
  detail_path: string;
  detail_url: string;
}
export interface JobListInvocationSummaryView {
  stage_spec_count: number;
  unknown_count: number;
}
export interface ListJobEventsQuery {
  limit?: number;
  offset?: number;
}
export interface ListJobsQuery {
  limit?: number;
  offset?: number;
  status?: JobStatusKind;
  workflow?: WorkflowKind;
  provider?: string;
  q?: string;
  job_ids?: string;
}
