/* eslint-disable */
/**
 * Generated by scripts/generate-types.mjs.
 * Do not edit by hand; update the source schema and run npm run generate.
 */

/**
 * Endpoint input, query, and output DTOs published by library-books.v1.schema.json.
 */
export type LibraryBooksSchema =
  | JobListView
  | LibraryBatchDeleteInput
  | LibraryBatchDeleteResultView
  | LibraryBookDetailView
  | LibraryBookListView
  | LibraryDeleteQuery
  | LibraryDeleteResultView
  | ListJobsQuery
  | ListLibraryBooksQuery;
/**
 * crate::models::common::WorkflowKind
 */
export type WorkflowKind = "book" | "ocr" | "translate" | "render";
/**
 * crate::models::common::JobStatusKind (serde rename_all snake_case)
 */
export type JobStatusKind = "queued" | "running" | "succeeded" | "failed" | "canceled";
export type JobStageStateView =
  "reused" | "queued" | "pending" | "in_progress" | "completed" | "failed" | "skipped";

export interface JobListView {
  items: JobListItemView[];
  invocation_summary: JobListInvocationSummaryView;
}
/**
 * job_types.rs :: JobListItemView — /api/v1/jobs 列表项，含 stage_snapshot 与 cover/thumbnail 双图。
 */
export interface JobListItemView {
  job_id: string;
  display_name: string;
  workflow: WorkflowKind;
  status: JobStatusKind;
  attempt: number;
  retry_count: number;
  last_retry_at: string | null;
  trace_id?: string | null;
  stage_snapshot: JobStageSnapshotView | null;
  background_snapshots: JobStageSnapshotView[];
  stages: JobStagesView;
  page_count?: number | null;
  source_file_name?: string | null;
  cover_url?: string | null;
  thumbnail_url?: string | null;
  output_pdf_ready: boolean;
  markdown_ready: boolean;
  bundle_ready: boolean;
  invocation?: InvocationSummaryView | null;
  created_at: string;
  updated_at: string;
  detail_path: string;
  detail_url: string;
}
/**
 * job_types.rs :: JobStageSnapshotView — 阶段快照（含 display_stage / stage / substage / lane / stage_detail / progress）。前端 normalize 与阶段进度均以此驱动。
 */
export interface JobStageSnapshotView {
  display_stage?: string | null;
  stage?: string | null;
  substage?: string | null;
  /**
   * main|background
   */
  lane?: string | null;
  stage_detail?: string | null;
  progress: JobProgressView;
}
/**
 * services/api/crates/retain-core/src/models/view/common.rs :: JobProgressView。current/total 为页/批计数（i64），percent 0-100，unit 标识页/批/步/percent。
 */
export interface JobProgressView {
  /**
   * 已完成计数，null=未知
   */
  current?: number | null;
  /**
   * 总数，null=未定/不定长
   */
  total?: number | null;
  percent?: number | null;
  /**
   * page|batch|step|percent|null，skip_serializing_if None
   */
  unit?: string | null;
}
export interface JobStagesView {
  ocr: JobStageRuntimeView;
  translation: JobStageRuntimeView;
  render: JobStageRuntimeView;
}
export interface JobStageRuntimeView {
  state: JobStageStateView;
  progress: JobProgressView;
}
export interface InvocationSummaryView {
  stage: string;
  input_protocol: string;
  stage_spec_schema_version: string;
}
export interface JobListInvocationSummaryView {
  stage_spec_count: number;
  unknown_count: number;
}
export interface LibraryBatchDeleteInput {
  ids: string[];
  force?: boolean;
}
export interface LibraryBatchDeleteResultView {
  items: LibraryDeleteResultView[];
}
export interface LibraryDeleteResultView {
  deleted: boolean;
  job_id: string;
  removed_paths: string[];
  removed_child_jobs: string[];
}
export interface LibraryBookDetailView {
  id: string;
  job_id: string;
  title: string;
  authors?: string | null;
  source_file_name?: string | null;
  page_count?: number | null;
  source_language?: string | null;
  target_language?: string | null;
  file_size_bytes?: number | null;
  status: JobStatusKind;
  stage?: string | null;
  progress: JobProgressView;
  cover_url: string | null;
  thumbnail_url: string | null;
  artifacts: ArtifactDisplayItemView[];
}
export interface ArtifactDisplayItemView {
  key: string;
  label: string;
  ready: boolean;
  kind: string;
  file_name?: string | null;
  size_bytes?: number | null;
  download_url?: string | null;
}
export interface LibraryBookListView {
  items: LibraryBookListItemView[];
}
/**
 * job_types.rs :: LibraryBookListItemView — 书架卡片。job_id 是主键（كر очередь: id 冗余为 job_id 别名），display_name 回退为 title/source_file_name。
 */
export interface LibraryBookListItemView {
  /**
   * book id (= job_id 去 ocr 后缀的归一化)
   */
  id: string;
  job_id: string;
  title: string;
  display_name: string;
  source_file_name?: string | null;
  authors?: string | null;
  page_count?: number | null;
  status: JobStatusKind;
  /**
   * 当前阶段 raw stage，null=未开始
   */
  stage?: string | null;
  stage_detail?: string | null;
  progress: JobProgressView;
  cover_url?: string | null;
  thumbnail_url?: string | null;
  output_pdf_ready: boolean;
  markdown_ready: boolean;
  bundle_ready: boolean;
  created_at: string;
  updated_at: string;
}
export interface LibraryDeleteQuery {
  force?: boolean;
}
export interface ListJobsQuery {
  limit?: number;
  offset?: number;
  status?: JobStatusKind;
  workflow?: WorkflowKind;
  provider?: string;
  q?: string;
  job_ids?: string;
}
export interface ListLibraryBooksQuery {
  limit?: number;
  offset?: number;
  q?: string;
  /**
   * 逗号分隔 job_id 白名单，对应 ListJobsQuery.job_ids
   */
  job_ids?: string;
}
